# Generated by Django 5.0.6 on 2024-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_aplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='applay/')),
                ('cover_letter', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Aplay',
        ),
    ]
