# Generated by Django 5.0.6 on 2024-08-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
